import type {
  Tenant,
  User,
  Source,
  CanonicalTransaction,
  ReconciliationRun,
  MatchDecision,
  Break,
  Case,
} from "@/lib/domain/types";
import type { MatchSuggestion } from "./client";

export interface Fixtures {
  tenants: Tenant[];
  users: User[];
  sources: Source[];
  transactions: CanonicalTransaction[];
  runs: ReconciliationRun[];
  matchDecisions: MatchDecision[];
  breaks: Break[];
  cases: Case[];
  suggestions: MatchSuggestion[];
}

export function buildFixtures(): Fixtures {
  // ---------------------------------------------------------------------------
  // Tenants
  // ---------------------------------------------------------------------------
  const tenants: Tenant[] = [
    { id: "tenant-acme", name: "Acme Capital", slug: "acme-capital" },
    { id: "tenant-globex", name: "Globex Markets", slug: "globex-markets" },
  ];

  // ---------------------------------------------------------------------------
  // Users (shared list returned for both tenants)
  // ---------------------------------------------------------------------------
  const users: User[] = [
    { id: "user-mia", name: "Mia", role: "operator" },
    { id: "user-sam", name: "Sam", role: "operator" },
    { id: "user-theo", name: "Theo", role: "approver" },
    { id: "user-ada", name: "Ada", role: "admin" },
  ];

  // ---------------------------------------------------------------------------
  // Sources
  // ---------------------------------------------------------------------------
  const sources: Source[] = [
    // Acme Capital sources
    {
      id: "src-acme-bank",
      tenantId: "tenant-acme",
      kind: "bank",
      name: "Acme Bank Statement",
      currency: "GBP",
      formatDialect: null,
    },
    {
      id: "src-acme-ledger",
      tenantId: "tenant-acme",
      kind: "ledger",
      name: "Acme General Ledger",
      currency: "GBP",
      formatDialect: null,
    },
    {
      id: "src-acme-cross",
      tenantId: "tenant-acme",
      kind: "cross_system",
      name: "Acme Cross-System Feed",
      currency: "USD",
      formatDialect: null,
    },
    // Globex Markets sources
    {
      id: "src-globex-bank",
      tenantId: "tenant-globex",
      kind: "bank",
      name: "Globex Bank Statement",
      currency: "USD",
      formatDialect: null,
    },
    {
      id: "src-globex-ledger",
      tenantId: "tenant-globex",
      kind: "ledger",
      name: "Globex General Ledger",
      currency: "USD",
      formatDialect: null,
    },
    {
      id: "src-globex-cross",
      tenantId: "tenant-globex",
      kind: "cross_system",
      name: "Globex Cross-System Feed",
      currency: "GBP",
      formatDialect: null,
    },
  ];

  // ---------------------------------------------------------------------------
  // Canonical Transactions (30+)
  // ---------------------------------------------------------------------------
  const transactions: CanonicalTransaction[] = [
    // Acme bank transactions
    {
      id: "txn-a001",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260501-001",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T09:00:00Z",
      amountMinor: 1000000,
      currency: "GBP",
      direction: "debit",
      counterparty: "Barclays",
      description: "Wire transfer out",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-a002",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260501-002",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T10:15:00Z",
      amountMinor: 500000,
      currency: "GBP",
      direction: "credit",
      counterparty: "HSBC",
      description: "Incoming payment",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-a003",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260502-001",
      valueDate: "2026-05-02",
      postedAt: "2026-05-02T08:30:00Z",
      amountMinor: 250000,
      currency: "GBP",
      direction: "debit",
      counterparty: "Lloyds",
      description: "FX settlement",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-a004",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260503-001",
      valueDate: "2026-05-03",
      postedAt: "2026-05-03T14:00:00Z",
      amountMinor: 750000,
      currency: "GBP",
      direction: "credit",
      counterparty: "NatWest",
      description: "Client receipt",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-a005",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260504-001",
      valueDate: "2026-05-04",
      postedAt: "2026-05-04T11:20:00Z",
      amountMinor: 320000,
      currency: "GBP",
      direction: "debit",
      counterparty: "Deutsche Bank",
      description: "Bond purchase",
      counterpartyBic: "DEUTDEFF",
      counterpartyAccount: "DE89370400440532013000",
    },
    // Acme ledger transactions
    {
      id: "txn-b001",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260501-001",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T09:05:00Z",
      amountMinor: 1000000,
      currency: "GBP",
      direction: "debit",
      description: "Wire transfer posting",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b002",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260501-002",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T10:20:00Z",
      amountMinor: 500000,
      currency: "GBP",
      direction: "credit",
      description: "Payment receipt posting",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b003",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260502-001",
      valueDate: "2026-05-02",
      postedAt: "2026-05-02T08:35:00Z",
      amountMinor: 250000,
      currency: "GBP",
      direction: "debit",
      description: "FX settlement posting",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b004",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260503-001",
      valueDate: "2026-05-03",
      postedAt: "2026-05-03T14:05:00Z",
      amountMinor: 750000,
      currency: "GBP",
      direction: "credit",
      description: "Client receipt posting",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b005",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260504-001",
      valueDate: "2026-05-04",
      postedAt: "2026-05-04T11:25:00Z",
      amountMinor: 319500,
      currency: "GBP",
      direction: "debit",
      description: "Bond purchase posting (partial)",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b006",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260505-001",
      valueDate: "2026-05-05",
      postedAt: "2026-05-05T09:00:00Z",
      amountMinor: 180000,
      currency: "GBP",
      direction: "credit",
      description: "Dividend receipt",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b007",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260505-002",
      valueDate: "2026-05-05",
      postedAt: "2026-05-05T10:00:00Z",
      amountMinor: 85000,
      currency: "GBP",
      direction: "debit",
      description: "Fee payment",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-b008",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260506-001",
      valueDate: "2026-05-06",
      postedAt: "2026-05-06T08:00:00Z",
      amountMinor: 430000,
      currency: "GBP",
      direction: "credit",
      description: "Unreconciled credit",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-c001",
      tenantId: "tenant-acme",
      sourceId: "src-acme-cross",
      externalRef: "CS-20260501-001",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T13:00:00Z",
      amountMinor: 200000,
      currency: "USD",
      direction: "debit",
      description: "Cross-system transfer A",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-c002",
      tenantId: "tenant-acme",
      sourceId: "src-acme-cross",
      externalRef: "CS-20260502-001",
      valueDate: "2026-05-02",
      postedAt: "2026-05-02T14:00:00Z",
      amountMinor: 200000,
      currency: "USD",
      direction: "debit",
      description: "Cross-system transfer B",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-c003",
      tenantId: "tenant-acme",
      sourceId: "src-acme-cross",
      externalRef: "CS-20260503-001",
      valueDate: "2026-05-03",
      postedAt: "2026-05-03T15:00:00Z",
      amountMinor: 150000,
      currency: "USD",
      direction: "credit",
      description: "Cross-system receipt",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-c004",
      tenantId: "tenant-acme",
      sourceId: "src-acme-cross",
      externalRef: "CS-20260510-001",
      valueDate: "2026-05-10",
      postedAt: "2026-05-10T09:30:00Z",
      amountMinor: 95000,
      currency: "USD",
      direction: "debit",
      description: "Duplicate suspected A",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-c005",
      tenantId: "tenant-acme",
      sourceId: "src-acme-cross",
      externalRef: "CS-20260510-002",
      valueDate: "2026-05-10",
      postedAt: "2026-05-10T09:31:00Z",
      amountMinor: 95000,
      currency: "USD",
      direction: "debit",
      description: "Duplicate suspected B",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    // Unmatched/break transactions (for break-pending etc.)
    {
      id: "txn-brk001",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260515-099",
      valueDate: "2026-05-15",
      postedAt: "2026-05-15T10:00:00Z",
      amountMinor: 125000,
      currency: "GBP",
      direction: "debit",
      counterparty: "Unknown Counterparty",
      description: "Pending investigation write-off candidate",
      counterpartyBic: "CHASGB2L",
      counterpartyAccount: "GB29NWBK60161331926819",
    },
    {
      id: "txn-brk002",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260516-010",
      valueDate: "2026-05-16",
      postedAt: "2026-05-16T11:00:00Z",
      amountMinor: 67500,
      currency: "GBP",
      direction: "credit",
      description: "Unmatched credit",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-brk003",
      tenantId: "tenant-acme",
      sourceId: "src-acme-ledger",
      externalRef: "GL-20260517-003",
      valueDate: "2026-05-17",
      postedAt: "2026-05-17T08:00:00Z",
      amountMinor: 340000,
      currency: "GBP",
      direction: "debit",
      description: "Partial match ledger side",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-brk004",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260517-004",
      valueDate: "2026-05-17",
      postedAt: "2026-05-17T08:05:00Z",
      amountMinor: 340500,
      currency: "GBP",
      direction: "debit",
      description: "Partial match bank side",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-brk005",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260518-005",
      valueDate: "2026-05-18",
      postedAt: "2026-05-18T12:00:00Z",
      amountMinor: 210000,
      currency: "GBP",
      direction: "debit",
      description: "Break type break",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-brk006",
      tenantId: "tenant-acme",
      sourceId: "src-acme-bank",
      externalRef: "BANK-20260519-006",
      valueDate: "2026-05-19",
      postedAt: "2026-05-19T09:00:00Z",
      amountMinor: 88000,
      currency: "GBP",
      direction: "credit",
      description: "Open break transaction",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-brk007",
      tenantId: "tenant-acme",
      sourceId: "src-acme-cross",
      externalRef: "CS-20260520-007",
      valueDate: "2026-05-20",
      postedAt: "2026-05-20T10:00:00Z",
      amountMinor: 55000,
      currency: "USD",
      direction: "debit",
      description: "Cross-system break",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    // Globex transactions
    {
      id: "txn-g001",
      tenantId: "tenant-globex",
      sourceId: "src-globex-bank",
      externalRef: "GBANK-20260501-001",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T09:00:00Z",
      amountMinor: 2000000,
      currency: "USD",
      direction: "debit",
      counterparty: "JPMorgan",
      description: "Globex wire out",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-g002",
      tenantId: "tenant-globex",
      sourceId: "src-globex-ledger",
      externalRef: "GGL-20260501-001",
      valueDate: "2026-05-01",
      postedAt: "2026-05-01T09:05:00Z",
      amountMinor: 2000000,
      currency: "USD",
      direction: "debit",
      description: "Globex GL wire posting",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-g003",
      tenantId: "tenant-globex",
      sourceId: "src-globex-bank",
      externalRef: "GBANK-20260503-001",
      valueDate: "2026-05-03",
      postedAt: "2026-05-03T11:00:00Z",
      amountMinor: 850000,
      currency: "USD",
      direction: "credit",
      description: "Globex client receipt",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-g004",
      tenantId: "tenant-globex",
      sourceId: "src-globex-ledger",
      externalRef: "GGL-20260503-001",
      valueDate: "2026-05-03",
      postedAt: "2026-05-03T11:05:00Z",
      amountMinor: 850000,
      currency: "USD",
      direction: "credit",
      description: "Globex GL client receipt",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
    {
      id: "txn-g005",
      tenantId: "tenant-globex",
      sourceId: "src-globex-bank",
      externalRef: "GBANK-20260510-001",
      valueDate: "2026-05-10",
      postedAt: "2026-05-10T14:00:00Z",
      amountMinor: 390000,
      currency: "USD",
      direction: "debit",
      description: "Globex unmatched item",
      counterpartyBic: null,
      counterpartyAccount: null,
    },
  ];

  // ---------------------------------------------------------------------------
  // Reconciliation Runs
  // ---------------------------------------------------------------------------
  const runs: ReconciliationRun[] = [
    // Acme runs (8)
    {
      id: "run-acme-001",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-01",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "completed",
      startedAt: "2026-05-01T18:00:00Z",
      completedAt: "2026-05-01T18:04:12Z",
      configVersion: "v1.2",
      stats: {
        matched: 95,
        unmatched: 3,
        partial: 2,
        duplicate: 0,
        breakCount: 3,
        matchRatePct: 95.0,
        valueAtRiskMinor: 125000,
      },
    },
    {
      id: "run-acme-002",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-02",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "completed",
      startedAt: "2026-05-02T18:00:00Z",
      completedAt: "2026-05-02T18:03:44Z",
      configVersion: "v1.2",
      stats: {
        matched: 102,
        unmatched: 1,
        partial: 2,
        duplicate: 1,
        breakCount: 2,
        matchRatePct: 97.1,
        valueAtRiskMinor: 67500,
      },
    },
    {
      id: "run-acme-003",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-03",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "completed",
      startedAt: "2026-05-03T18:00:00Z",
      completedAt: "2026-05-03T18:05:21Z",
      configVersion: "v1.2",
      stats: {
        matched: 88,
        unmatched: 4,
        partial: 3,
        duplicate: 0,
        breakCount: 4,
        matchRatePct: 91.7,
        valueAtRiskMinor: 340000,
      },
    },
    {
      id: "run-acme-004",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-04",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "completed",
      startedAt: "2026-05-04T18:00:00Z",
      completedAt: "2026-05-04T18:02:58Z",
      configVersion: "v1.2",
      stats: {
        matched: 110,
        unmatched: 2,
        partial: 1,
        duplicate: 0,
        breakCount: 2,
        matchRatePct: 96.5,
        valueAtRiskMinor: 500000,
      },
    },
    {
      id: "run-acme-005",
      tenantId: "tenant-acme",
      name: "Cross-System Recon 2026-05-10",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-cross",
      status: "completed",
      startedAt: "2026-05-10T20:00:00Z",
      completedAt: "2026-05-10T20:07:33Z",
      configVersion: "v1.1",
      stats: {
        matched: 45,
        unmatched: 2,
        partial: 0,
        duplicate: 2,
        breakCount: 3,
        matchRatePct: 89.8,
        valueAtRiskMinor: 190000,
      },
    },
    {
      id: "run-acme-006",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-15",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "completed",
      startedAt: "2026-05-15T18:00:00Z",
      completedAt: "2026-05-15T18:06:11Z",
      configVersion: "v1.3",
      stats: {
        matched: 120,
        unmatched: 5,
        partial: 3,
        duplicate: 1,
        breakCount: 7,
        matchRatePct: 92.3,
        valueAtRiskMinor: 875000,
      },
    },
    {
      id: "run-acme-007",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-20",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "failed",
      startedAt: "2026-05-20T18:00:00Z",
      completedAt: "2026-05-20T18:01:05Z",
      configVersion: "v1.3",
      stats: {
        matched: 0,
        unmatched: 0,
        partial: 0,
        duplicate: 0,
        breakCount: 0,
        matchRatePct: 0,
        valueAtRiskMinor: 0,
      },
    },
    {
      id: "run-acme-008",
      tenantId: "tenant-acme",
      name: "Daily Bank-GL 2026-05-23",
      sourceAId: "src-acme-bank",
      sourceBId: "src-acme-ledger",
      status: "running",
      startedAt: "2026-05-23T18:00:00Z",
      configVersion: "v1.3",
      stats: {
        matched: 22,
        unmatched: 1,
        partial: 0,
        duplicate: 0,
        breakCount: 1,
        matchRatePct: 95.6,
        valueAtRiskMinor: 88000,
      },
    },
    // Globex runs (3)
    {
      id: "run-globex-001",
      tenantId: "tenant-globex",
      name: "Globex Daily Recon 2026-05-01",
      sourceAId: "src-globex-bank",
      sourceBId: "src-globex-ledger",
      status: "completed",
      startedAt: "2026-05-01T19:00:00Z",
      completedAt: "2026-05-01T19:05:30Z",
      configVersion: "v2.0",
      stats: {
        matched: 78,
        unmatched: 1,
        partial: 0,
        duplicate: 0,
        breakCount: 1,
        matchRatePct: 98.7,
        valueAtRiskMinor: 390000,
      },
    },
    {
      id: "run-globex-002",
      tenantId: "tenant-globex",
      name: "Globex Daily Recon 2026-05-10",
      sourceAId: "src-globex-bank",
      sourceBId: "src-globex-ledger",
      status: "completed",
      startedAt: "2026-05-10T19:00:00Z",
      completedAt: "2026-05-10T19:04:12Z",
      configVersion: "v2.0",
      stats: {
        matched: 65,
        unmatched: 2,
        partial: 1,
        duplicate: 0,
        breakCount: 2,
        matchRatePct: 95.6,
        valueAtRiskMinor: 1200000,
      },
    },
    {
      id: "run-globex-003",
      tenantId: "tenant-globex",
      name: "Globex Daily Recon 2026-05-23",
      sourceAId: "src-globex-bank",
      sourceBId: "src-globex-ledger",
      status: "running",
      startedAt: "2026-05-23T19:00:00Z",
      configVersion: "v2.1",
      stats: {
        matched: 10,
        unmatched: 0,
        partial: 0,
        duplicate: 0,
        breakCount: 0,
        matchRatePct: 100,
        valueAtRiskMinor: 0,
      },
    },
  ];

  // ---------------------------------------------------------------------------
  // Match Decisions
  // ---------------------------------------------------------------------------
  const matchDecisions: MatchDecision[] = [
    {
      id: "md-001",
      runId: "run-acme-001",
      type: "matched",
      txnIds: ["txn-a001", "txn-b001"],
      score: 1.0,
      configVersion: "v1.2",
    },
    {
      id: "md-002",
      runId: "run-acme-001",
      type: "matched",
      txnIds: ["txn-a002", "txn-b002"],
      score: 1.0,
      configVersion: "v1.2",
    },
    {
      id: "md-003",
      runId: "run-acme-001",
      type: "matched",
      txnIds: ["txn-a003", "txn-b003"],
      score: 0.98,
      configVersion: "v1.2",
    },
    {
      id: "md-004",
      runId: "run-acme-001",
      type: "matched",
      txnIds: ["txn-a004", "txn-b004"],
      score: 1.0,
      configVersion: "v1.2",
    },
    {
      id: "md-005",
      runId: "run-acme-001",
      type: "partial",
      txnIds: ["txn-a005", "txn-b005"],
      score: 0.72,
      configVersion: "v1.2",
    },
    {
      id: "md-006",
      runId: "run-acme-005",
      type: "duplicate",
      txnIds: ["txn-c004", "txn-c005"],
      score: 0.99,
      configVersion: "v1.1",
    },
    {
      id: "md-007",
      runId: "run-acme-006",
      type: "partial",
      txnIds: ["txn-brk003", "txn-brk004"],
      score: 0.68,
      configVersion: "v1.3",
    },
  ];

  // ---------------------------------------------------------------------------
  // Breaks (15+ for tenant-acme covering all BreakTypes and AgeingBuckets)
  // ---------------------------------------------------------------------------
  const breaks: Break[] = [
    // break-pending: the must-have for four-eyes flow
    {
      id: "break-pending",
      tenantId: "tenant-acme",
      runId: "run-acme-006",
      caseId: "case-pending",
      type: "unmatched",
      status: "pending_approval",
      ageingDays: 8,
      ageingBucket: "8-30d",
      valueMinor: 125000,
      currency: "GBP",
      assigneeId: "user-mia",
      txnIds: ["txn-brk001"],
      openedAt: "2026-05-15T10:30:00Z",
    },
    {
      id: "break-001",
      tenantId: "tenant-acme",
      runId: "run-acme-001",
      caseId: "case-001",
      type: "unmatched",
      status: "open",
      ageingDays: 22,
      ageingBucket: "8-30d",
      valueMinor: 67500,
      currency: "GBP",
      txnIds: ["txn-brk002"],
      openedAt: "2026-05-01T19:00:00Z",
    },
    {
      id: "break-002",
      tenantId: "tenant-acme",
      runId: "run-acme-003",
      caseId: "case-002",
      type: "partial",
      status: "investigating",
      ageingDays: 20,
      ageingBucket: "8-30d",
      valueMinor: 500,
      currency: "GBP",
      assigneeId: "user-sam",
      txnIds: ["txn-brk003", "txn-brk004"],
      openedAt: "2026-05-03T19:00:00Z",
    },
    {
      id: "break-003",
      tenantId: "tenant-acme",
      runId: "run-acme-006",
      caseId: "case-003",
      type: "break",
      status: "open",
      ageingDays: 5,
      ageingBucket: "2-7d",
      valueMinor: 210000,
      currency: "GBP",
      txnIds: ["txn-brk005"],
      openedAt: "2026-05-18T13:00:00Z",
    },
    {
      id: "break-004",
      tenantId: "tenant-acme",
      runId: "run-acme-008",
      caseId: "case-004",
      type: "unmatched",
      status: "open",
      ageingDays: 0,
      ageingBucket: "0-1d",
      valueMinor: 88000,
      currency: "GBP",
      txnIds: ["txn-brk006"],
      openedAt: "2026-05-23T18:30:00Z",
    },
    {
      id: "break-005",
      tenantId: "tenant-acme",
      runId: "run-acme-005",
      caseId: "case-005",
      type: "duplicate",
      status: "investigating",
      ageingDays: 13,
      ageingBucket: "8-30d",
      valueMinor: 95000,
      currency: "USD",
      assigneeId: "user-theo",
      txnIds: ["txn-c004", "txn-c005"],
      openedAt: "2026-05-10T21:00:00Z",
    },
    {
      id: "break-006",
      tenantId: "tenant-acme",
      runId: "run-acme-005",
      caseId: "case-006",
      type: "break",
      status: "open",
      ageingDays: 3,
      ageingBucket: "2-7d",
      valueMinor: 55000,
      currency: "USD",
      txnIds: ["txn-c002"],
      openedAt: "2026-05-20T11:00:00Z",
    },
    {
      id: "break-007",
      tenantId: "tenant-acme",
      runId: "run-acme-003",
      caseId: "case-007",
      type: "unmatched",
      status: "open",
      ageingDays: 35,
      ageingBucket: "30d+",
      valueMinor: 430000,
      currency: "GBP",
      txnIds: ["txn-b008"],
      openedAt: "2026-04-18T09:00:00Z",
    },
    {
      id: "break-008",
      tenantId: "tenant-acme",
      runId: "run-acme-002",
      caseId: "case-008",
      type: "partial",
      status: "resolved",
      ageingDays: 21,
      ageingBucket: "8-30d",
      valueMinor: 500,
      currency: "GBP",
      assigneeId: "user-ada",
      txnIds: ["txn-a005", "txn-b005"],
      openedAt: "2026-05-02T19:00:00Z",
    },
    {
      id: "break-009",
      tenantId: "tenant-acme",
      runId: "run-acme-001",
      caseId: "case-009",
      type: "unmatched",
      status: "written_off",
      ageingDays: 42,
      ageingBucket: "30d+",
      valueMinor: 15000,
      currency: "GBP",
      assigneeId: "user-ada",
      txnIds: ["txn-b006"],
      openedAt: "2026-04-11T09:00:00Z",
    },
    {
      id: "break-010",
      tenantId: "tenant-acme",
      runId: "run-acme-004",
      caseId: "case-010",
      type: "break",
      status: "investigating",
      ageingDays: 19,
      ageingBucket: "8-30d",
      valueMinor: 320000,
      currency: "GBP",
      assigneeId: "user-mia",
      txnIds: ["txn-a005"],
      openedAt: "2026-05-04T19:00:00Z",
    },
    {
      id: "break-011",
      tenantId: "tenant-acme",
      runId: "run-acme-006",
      caseId: "case-011",
      type: "unmatched",
      status: "open",
      ageingDays: 1,
      ageingBucket: "0-1d",
      valueMinor: 180000,
      currency: "GBP",
      txnIds: ["txn-b006"],
      openedAt: "2026-05-22T14:00:00Z",
    },
    {
      id: "break-012",
      tenantId: "tenant-acme",
      runId: "run-acme-006",
      caseId: "case-012",
      type: "duplicate",
      status: "open",
      ageingDays: 6,
      ageingBucket: "2-7d",
      valueMinor: 85000,
      currency: "GBP",
      txnIds: ["txn-b007"],
      openedAt: "2026-05-17T16:00:00Z",
    },
    {
      id: "break-013",
      tenantId: "tenant-acme",
      runId: "run-acme-003",
      caseId: "case-013",
      type: "partial",
      status: "open",
      ageingDays: 38,
      ageingBucket: "30d+",
      valueMinor: 320000,
      currency: "GBP",
      txnIds: ["txn-a005", "txn-b005"],
      openedAt: "2026-04-15T09:00:00Z",
    },
    {
      id: "break-014",
      tenantId: "tenant-acme",
      runId: "run-acme-006",
      caseId: "case-014",
      type: "break",
      status: "investigating",
      ageingDays: 7,
      ageingBucket: "2-7d",
      valueMinor: 750000,
      currency: "GBP",
      assigneeId: "user-sam",
      txnIds: ["txn-a004"],
      openedAt: "2026-05-16T10:00:00Z",
    },
    // Globex break
    {
      id: "break-globex-001",
      tenantId: "tenant-globex",
      runId: "run-globex-001",
      caseId: "case-globex-001",
      type: "unmatched",
      status: "open",
      ageingDays: 22,
      ageingBucket: "8-30d",
      valueMinor: 390000,
      currency: "USD",
      txnIds: ["txn-g005"],
      openedAt: "2026-05-01T20:00:00Z",
    },
  ];

  // ---------------------------------------------------------------------------
  // Cases
  // ---------------------------------------------------------------------------
  const cases: Case[] = [
    // case-pending: the must-have for four-eyes flow
    {
      id: "case-pending",
      breakId: "break-pending",
      assigneeId: "user-mia",
      status: "pending_approval",
      events: [
        {
          id: "evt-pending-001",
          kind: "assignment",
          actorId: "user-ada",
          at: "2026-05-15T11:00:00Z",
          payload: { assigneeId: "user-mia" },
        },
        {
          id: "evt-pending-002",
          kind: "comment",
          actorId: "user-mia",
          at: "2026-05-16T09:00:00Z",
          payload: { text: "Reviewed transaction details. Looks like a write-off candidate." },
        },
        {
          id: "evt-pending-003",
          kind: "write_off_proposed",
          actorId: "user-mia",
          at: "2026-05-16T09:30:00Z",
          payload: { reason: "Counterparty confirmed transaction cannot be matched. Amount below materiality threshold." },
        },
        {
          id: "evt-pending-004",
          kind: "approval_requested",
          actorId: "user-mia",
          at: "2026-05-16T09:35:00Z",
          payload: { resolution: "write_off" },
        },
      ],
    },
    {
      id: "case-001",
      breakId: "break-001",
      status: "open",
      events: [
        {
          id: "evt-001-001",
          kind: "comment",
          actorId: "user-sam",
          at: "2026-05-02T10:00:00Z",
          payload: { text: "Opened for investigation." },
        },
      ],
    },
    {
      id: "case-002",
      breakId: "break-002",
      assigneeId: "user-sam",
      status: "investigating",
      events: [
        {
          id: "evt-002-001",
          kind: "assignment",
          actorId: "user-ada",
          at: "2026-05-04T09:00:00Z",
          payload: { assigneeId: "user-sam" },
        },
        {
          id: "evt-002-002",
          kind: "comment",
          actorId: "user-sam",
          at: "2026-05-05T11:00:00Z",
          payload: { text: "Partial match due to rounding difference of £5.00. Verifying with bank." },
        },
      ],
    },
    {
      id: "case-003",
      breakId: "break-003",
      status: "open",
      events: [],
    },
    {
      id: "case-004",
      breakId: "break-004",
      status: "open",
      events: [],
    },
    {
      id: "case-005",
      breakId: "break-005",
      assigneeId: "user-theo",
      status: "investigating",
      events: [
        {
          id: "evt-005-001",
          kind: "assignment",
          actorId: "user-ada",
          at: "2026-05-11T09:00:00Z",
          payload: { assigneeId: "user-theo" },
        },
        {
          id: "evt-005-002",
          kind: "comment",
          actorId: "user-theo",
          at: "2026-05-12T14:00:00Z",
          payload: { text: "Confirmed duplicate submission. Investigating source system." },
        },
      ],
    },
    {
      id: "case-006",
      breakId: "break-006",
      status: "open",
      events: [],
    },
    {
      id: "case-007",
      breakId: "break-007",
      status: "open",
      events: [
        {
          id: "evt-007-001",
          kind: "comment",
          actorId: "user-mia",
          at: "2026-04-20T10:00:00Z",
          payload: { text: "Aging break — needs escalation if not resolved by end of month." },
        },
      ],
    },
    {
      id: "case-008",
      breakId: "break-008",
      assigneeId: "user-ada",
      status: "resolved",
      events: [
        {
          id: "evt-008-001",
          kind: "assignment",
          actorId: "user-ada",
          at: "2026-05-03T09:00:00Z",
          payload: { assigneeId: "user-ada" },
        },
        {
          id: "evt-008-002",
          kind: "comment",
          actorId: "user-ada",
          at: "2026-05-04T16:00:00Z",
          payload: { text: "Rounding tolerance confirmed. Resolved." },
        },
      ],
    },
    {
      id: "case-009",
      breakId: "break-009",
      assigneeId: "user-ada",
      status: "written_off",
      events: [
        {
          id: "evt-009-001",
          kind: "write_off_proposed",
          actorId: "user-ada",
          at: "2026-04-15T11:00:00Z",
          payload: { reason: "Amount below materiality threshold. Writing off." },
        },
        {
          id: "evt-009-002",
          kind: "approval_requested",
          actorId: "user-ada",
          at: "2026-04-15T11:05:00Z",
          payload: { resolution: "write_off" },
        },
        {
          id: "evt-009-003",
          kind: "approved",
          actorId: "user-theo",
          at: "2026-04-15T14:00:00Z",
          payload: {},
        },
      ],
    },
    {
      id: "case-010",
      breakId: "break-010",
      assigneeId: "user-mia",
      status: "investigating",
      events: [
        {
          id: "evt-010-001",
          kind: "assignment",
          actorId: "user-ada",
          at: "2026-05-05T09:00:00Z",
          payload: { assigneeId: "user-mia" },
        },
      ],
    },
    {
      id: "case-011",
      breakId: "break-011",
      status: "open",
      events: [],
    },
    {
      id: "case-012",
      breakId: "break-012",
      status: "open",
      events: [],
    },
    {
      id: "case-013",
      breakId: "break-013",
      status: "open",
      events: [
        {
          id: "evt-013-001",
          kind: "comment",
          actorId: "user-mia",
          at: "2026-04-20T09:00:00Z",
          payload: { text: "Long-running partial match. Needs review." },
        },
      ],
    },
    {
      id: "case-014",
      breakId: "break-014",
      assigneeId: "user-sam",
      status: "investigating",
      events: [
        {
          id: "evt-014-001",
          kind: "assignment",
          actorId: "user-ada",
          at: "2026-05-17T10:30:00Z",
          payload: { assigneeId: "user-sam" },
        },
        {
          id: "evt-014-002",
          kind: "comment",
          actorId: "user-sam",
          at: "2026-05-18T09:00:00Z",
          payload: { text: "Checking with back office on large break." },
        },
      ],
    },
    // Globex case
    {
      id: "case-globex-001",
      breakId: "break-globex-001",
      status: "open",
      events: [],
    },
  ];

  // ---------------------------------------------------------------------------
  // Match Suggestions
  // ---------------------------------------------------------------------------
  const suggestions: MatchSuggestion[] = [
    {
      id: "sug-pending-001",
      txnIds: ["txn-brk001", "txn-b008"],
      score: 0.82,
      rationale: "Same value date and amount within 5% tolerance. Likely same underlying trade.",
    },
    {
      id: "sug-pending-002",
      txnIds: ["txn-brk001", "txn-b006"],
      score: 0.61,
      rationale: "Amount difference is £55,000. Possible partial match after netting.",
    },
    {
      id: "sug-007-001",
      txnIds: ["txn-b008", "txn-a004"],
      score: 0.55,
      rationale: "Same counterparty direction. Low confidence due to date discrepancy.",
    },
    {
      id: "sug-010-001",
      txnIds: ["txn-a005", "txn-b005"],
      score: 0.91,
      rationale: "Near-match: same direction, amount differs by £500 (rounding).",
    },
  ];

  return {
    tenants,
    users,
    sources,
    transactions,
    runs,
    matchDecisions,
    breaks,
    cases,
    suggestions,
  };
}
